[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
camino = "E3UTHzf4Dc1pcu5fBZGN9WashSnbrVK1ht9tzQL2m3pL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"